-- STG content-opportunity monitor — schema
-- Postgres / Supabase flavor. The local SQLite fallback creates equivalent
-- tables itself (see src/store.py), so you only need to run this if you use
-- Supabase. In the Supabase SQL editor, paste and run this whole file.

-- Kept opportunities awaiting human review.
create table if not exists content_opportunities (
    id                 bigint generated by default as identity primary key,
    source             text        not null default 'reddit',
    source_id          text        not null,             -- e.g. t3_abc123 / t1_def456
    subreddit          text        not null,
    permalink          text        not null,
    captured_at        timestamptz not null default now(),
    relevance_score    integer     not null,
    rationale          text,
    selfpromo_risk     text        not null default 'low',  -- low | medium | high
    draft_comment      text,
    notes_for_reviewer text,
    status             text        not null default 'pending', -- pending | posted | discarded
    unique (source, source_id)
);

create index if not exists idx_opportunities_status
    on content_opportunities (status);
create index if not exists idx_opportunities_score
    on content_opportunities (relevance_score desc);

-- Dedup ledger: every source id we have already processed (drafted or skipped),
-- so the same thread is never scored/drafted twice.
create table if not exists seen_sources (
    source_id   text        primary key,
    captured_at timestamptz not null default now()
);
